function probability_bound = get_probability_bound(probability_bound, varargin)

  probability_bound = ...
      @(problem, train_ind, observed_labels, test_ind, num_positives) ...
      probability_bound(problem, train_ind, observed_labels, test_ind, ...
                        num_positives, varargin{:});

end